---
title: "Demographics"
author: "Laura Symul"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  bookdown::html_document2: 
    theme: flatly
    highlight: haddock
    toc: yes
    toc_float: true
    toc_depth: 5
    number_sections: true
    fig_caption: true
---


```{r data_presentation_demographics librairies and stuff, include = FALSE, eval = TRUE}
source("Scripts/00_setup.R")
```


```{r data_presentation_demographics setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
options(scipen=999)
```


```{r data_presentation_demographics load data}
load(paste0(IO$output_data, "users.Rdata"),verbose = TRUE)
load(paste0(IO$output_data, "cycles.Rdata"),verbose = TRUE)
```



## Demographics


```{r data_presentation_demographics age and bmi cat}

users$age_cat = cut(users$age, breaks = breaks$age)
users$bmi = users$weight / (users$height/100)^2
users$bmi_cat = cut(users$bmi, breaks = breaks$bmi)

cycles$age = users$age[match(cycles$user_id, users$user_id)]
cycles$age_cat = cut(cycles$age, breaks = breaks$age)
cycles$bmi = users$bmi[match(cycles$user_id, users$user_id)]
cycles$bmi_cat = cut(cycles$bmi, breaks = breaks$bmi)


save(users, file = paste0(IO$output_data, "users.Rdata"))
file.copy(from = paste0(IO$output_data, "users.Rdata"), to =  paste0(IO$tmp_data, "users_with_demographics.Rdata"), overwrite = TRUE)


save(cycles, file = paste0(IO$output_data, "cycles.Rdata"))
file.copy(from = paste0(IO$output_data, "cycles.Rdata"), to =  paste0(IO$tmp_data, "cycles_with_demographics.Rdata"), overwrite = TRUE)

```


### Number of users in each considered category


```{r data_presentation_demographics number of users in each considered category}


agg_users = aggregate(user_id ~ age_cat + bmi_cat + BC, users, length)
colnames(agg_users)[which(colnames(agg_users) == "user_id")] = "n_users"

agg_cycles = aggregate(cycle_id ~ age_cat + bmi_cat + BC, cycles, length)
colnames(agg_cycles)[which(colnames(agg_cycles) == "cycle_id")] = "n_cycles"

agg = merge(agg_users, agg_cycles, all = TRUE)

save(agg, file = paste0(IO$out_Rdata, "number_of_users_and_cycles_per_category.Rdata"))


users$BC = factor(users$BC, levels = par$users_BC_dict$name)
g = ggplot(users, aes(x = age, fill = BC))
g + geom_histogram(binwidth = 1) + facet_grid(BC ~.) + scale_fill_manual(values = cols$BC_users)

g = ggplot(users[users$country %in% names(sort(table(users$country),decreasing = TRUE))[1:9],], 
           aes(x = age, fill = country))
g + geom_histogram(binwidth = 1) + facet_wrap(country ~.) + guides(fill = FALSE)


g = ggplot(agg[agg$BC %in% par$BC_dict$name,], aes(y = BC, x= 0,   col = BC)) + 
  facet_grid(bmi_cat ~ age_cat) + 
  geom_text(aes(label = n_users)) + 
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.ticks = element_blank(),
        axis.text.x = element_blank()) + 
  guides(color = FALSE, size = FALSE) + xlab("") + ylab("") + 
  ggtitle("Number of users per category of age (horizontal) and bmi (vertical)")

g


agg$BC = factor(agg$BC, levels = par$users_BC_dict$name)
g = ggplot(agg, aes(y = BC, x= 0,   col = BC)) + 
  facet_grid(bmi_cat ~ age_cat) + 
  geom_text(aes(label = n_users)) + 
  scale_color_manual(values = cols$BC_users)+
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.ticks = element_blank(),
        axis.text.x = element_blank()) + 
  guides(color = FALSE, size = FALSE) + xlab("") + ylab("") + 
  ggtitle("Number of users per category of age (horizontal) and bmi (vertical)")

g


g = ggplot(agg[agg$BC %in% par$BC_dict$name,], aes(y = BC, x= 0,   col = BC)) + 
  facet_grid(bmi_cat ~ age_cat) + 
  geom_text(aes(label = n_cycles)) + 
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.ticks = element_blank(),
        axis.text.x = element_blank()) + 
  guides(color = FALSE, size = FALSE) + xlab("") + ylab("") +
  ggtitle("Number of cycles per category of age (horizontal) and bmi (vertical)")
g

```




