---
title: "Keeping users and cycles from re-classified cycles"
author: "Laura Symul"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  bookdown::html_document2: 
    theme: flatly
    highlight: haddock
    toc: yes
    toc_float: true
    toc_depth: 5
    number_sections: true
    fig_caption: true
---



```{r data_prep_BC_user_post_filtering librairies and stuff, include = FALSE, eval = TRUE}
source("Scripts/00_setup.R")
```


```{r data_prep_BC_user_post_filtering setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
options(scipen=999)
```


## Filtering users, cycles and days to only keep properly re-classified cycles


### Loading re-classified cycles


```{r data_prep_BC_user_post_filtering Loading reclassified cycles and users}

load(file = paste0(IO$tmp_data,"cycles_BC_re_classification.Rdata"), verbose = TRUE)
cycles_BC = cycles
rm(cycles)

load(paste0(IO$output_data, "users.Rdata"), verbose = TRUE)


```

```{r data_prep_BC_user_post_filtering counting users for whom all their cycles are "unclear"}
cycle_ids = cycles_BC$cycle_id[which(cycles_BC$BC %in% par$BC_dict$name)]
length(cycle_ids)/nrow(cycles_BC)

user_ids = unique(cycles_BC$user_id[which(cycles_BC$BC %in% par$BC_dict$name)])
length(user_ids)

dim(users)

save(cycle_ids, file = paste0(IO$tmp_data, "cycle_ids_BC_reclassified.Rdata"))
```



### users


```{r data_prep_BC_user_post_filtering adding BC to users}

o = order(cycles_BC$user_id_n, cycles_BC$cycle_nb)
if(any(unique(diff(o))>1)){cycles_BC = cycles_BC[o,]}

# adding BC
user_BC_agg = aggregate(BC ~ user_id, cycles_BC[which(cycles_BC$BC %in% par$BC_dict$name),], function(x){paste0(sort(unique(x)), collapse = " - ")})
user_BC_agg$BC[which(!(user_BC_agg$BC %in% par$BC_dict$name))] = "both"
users$BC = user_BC_agg$BC[match(users$user_id, user_BC_agg$user_id)]
users$BC[is.na(users$BC)] = "unclear"

# adding number of stretches
agg = aggregate(stretch_id ~ user_id, cycles_BC[!is.na(cycles_BC$stretch_id),], lu)
users$n_stretches = agg$stretch_id[match(users$user_id, agg$user_id)]
users$n_stretches[is.na(users$n_stretches)] = 0

# adding first and last BC + transition type
agg = aggregate(BC ~ user_id, cycles_BC[which(cycles_BC$BC %in% par$BC_dict$name),], first)
users$BC_first = agg$BC[match(users$user_id, agg$user_id)]
agg = aggregate(BC ~ user_id, cycles_BC[which(cycles_BC$BC %in% par$BC_dict$name),], last)
users$BC_last = agg$BC[match(users$user_id, agg$user_id)]
users$BC_trans = case_when((users$BC == "unclear") ~ "unknown",
                           (users$BC_first == users$BC_last) & (users$BC != "both") ~ "0",
                           (users$BC_first == users$BC_last) & (users$BC == "both") ~ "mult",
                           (users$BC_first != users$BC_last) & (users$BC_first == "pill") ~ "off pill",
                           (users$BC_first != users$BC_last) & (users$BC_last == "pill") ~ "on pill",
                           TRUE ~ "NA")

# adding # of cycles with BC not "unclear"

users$n_cycles_o


```

```{r data_prep_BC_user_post_filtering saving users}
save(users, file = paste0(IO$output_data, "users.Rdata"))
file.copy(from = paste0(IO$output_data, "users.Rdata"), to = paste0(IO$tmp_data,"users_with_BC_reclassified.Rdata"), overwrite = TRUE)
```


```{r data_prep_BC_user_post_filtering users statistics}
table_BC = table(users$BC)
table_BC
round(table_BC/sum(table_BC)*100,2)

table_BC = table(users$birth_control, users$BC)
table_BC
round(table_BC/apply(table_BC,1,sum)*100,2)

table_stretches = table(users$n_stretches)
table_stretches
round(table_stretches/sum(table_stretches)*100,2)

table_BC_trans = table(users$BC_trans)
table_BC_trans
round(table_BC_trans/sum(table_BC_trans)*100,2)

```





```{r data_prep_BC_user_post_filtering stretches BC transitions}

stretches = aggregate(BC ~ stretch_id, cycles_BC[which(cycles_BC$BC %in% par$BC_dict$name),], function(x){paste0(rle(x)$values, collapse = " - ")})

stretches$BC_o = stretches$BC
stretches$BC[grep("none / condoms - pill",stretches$BC)] = "on pill"
stretches$BC[grep("pill - none / condoms",stretches$BC)] = "off pill"
stretches$BC[grep("pill - none / condoms - pill",stretches$BC)] = "off-on pill"
stretches$BC[grep("none / condoms - pill - none / condoms",stretches$BC)] = "on-off pill"
stretches$BC[nchar(stretches$BC) > 38 ] = "mult. trans."

table_BC = table(stretches$BC)
table_BC
round(table_BC/sum(table_BC)*100,2)


tmp_rle = rle(sort(stretches$BC))
df = data.frame(categories = tmp_rle$values, n = tmp_rle$lengths)
rm(tmp_rle)
df$categories = factor(df$categories, levels = df$categories[order(df$n)])
ggplot(df, aes(x = categories, y = n)) + geom_bar(stat = "identity") + coord_flip() + geom_text(aes(label = n))
rm(df)

```


```{r data_prep_BC_user_post_filtering saving stretches}
save(stretches, file = paste0(IO$output_data, "stretches.Rdata"))
file.copy(from = paste0(IO$output_data, "stretches.Rdata"), to = paste0(IO$tmp_data,"stretches.Rdata"), overwrite = TRUE)
```



### Days


```{r data_prep_BC_user_post_filtering filtering days - function}

filter_day_after_BC_re_class = function(filename = ""){
  
  cat(filename,"\n")
  load(paste0(input_days_folder, filename), verbose = TRUE)
  cat(filename," : days table loaded \n")
  
  #filtering on BC  
  days = days[which(days$cycle_id %in% cycle_ids),]
  cat(filename," : days table filtered on BC \n")

  
  # augmenting days with users and cycles characteristics
  days$BC = cycles_BC$BC[match(days$cycle_id, cycles_BC$cycle_id)]
  m = match(days$user_id, users$user_id)
  days$age = users$age[m]
  days$country = users$country[m]
  days$height = users$height[m]
  days$weight = users$weight[m]
  
  cat(filename," : days table augmented \n")
  
  # saving full tracking days
  save(days, file = paste0(output_days_folder_full, filename))
  cat(filename," : full tracking saved \n")
  
  # only keep pill, TB, period and n_logs
  j = which(days$category %in% c("pill_hbc","n_logs","period","pain"))
  length(j)/nrow(days)
  days = days[j,]
  
  #save days table
  save(days, file = paste0(output_days_folder, filename))
  cat(filename," : saved \n")
  cat(filename," : done \n")
}
  
```



```{r data_prep_BC_user_post_filtering filtering days}

if(!("cycle_ids" %in% ls())){load(file = paste0(IO$tmp_data, "cycle_ids_BC_reclassified.Rdata"), verbose = TRUE)}
if(!("cycles_BC" %in% ls())){load(file = paste0(IO$tmp_data, "cycles_BC_re_classification.Rdata"), verbose = TRUE); cycles_BC = cycles; rm(cycles)}
if(!("users" %in% ls())){load(file = paste0(IO$output_data, "users.Rdata"), verbose = TRUE)}

#input
input_days_folder = paste0(IO$tmp_data,"days_with_m_centered_cycle_ids/")
filenames = list.files(input_days_folder)

#output filtered days
output_days_folder = paste0(IO$tmp_data,"days_after_BC_filtering/")
if(dir.exists(output_days_folder)){unlink(output_days_folder, recursive = TRUE)}
dir.create(output_days_folder)

#output full tracking ( = all logs for the properly re-classified cycles)
output_days_folder_full = paste0(IO$tmp_data,"days_after_BC_filtering_full_tracking/")
if(dir.exists(output_days_folder_full)){unlink(output_days_folder_full, recursive = TRUE)}
dir.create(output_days_folder_full)


#filenames = filenames[sample(1:length(filenames),20)]


# now()
# tic()
# cl = makeCluster(min(par$n_cores, length(filenames)), outfile="")
# registerDoParallel(cl)
# foreach(this_filename = filenames,
#         .export = c("cycle_ids","cycles_BC","users","input_days_folder","output_days_folder","output_days_folder_full")
#         ) %dopar% {filter_day_after_BC_re_class(filename = this_filename)}
# stopCluster(cl)
# tac(chunck_name = "data_prep_BC_user_post_filtering filtering days")

tic()
foreach(this_filename = filenames) %do% {filter_day_after_BC_re_class(filename = this_filename)}
tac(chunck_name = "data_prep_BC_user_post_filtering filtering days")

```


```{r data_prep_BC_user_post_filtering copy to output folder}
copy_days_tmp2out(output_days_folder_full)
file.rename(from = paste0(IO$output_data,"days"),to = paste0(IO$output_data,"days_full_tracking"))

copy_days_tmp2out(output_days_folder)
```


