---
title: "Formating data"
author: "Laura Symul"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  bookdown::html_document2: 
    theme: flatly
    highlight: haddock
    toc: yes
    toc_float: true
    toc_depth: 5
    number_sections: true
    fig_caption: true
---



```{r data_prep_format librairies and stuff, include = FALSE, eval = TRUE}
source("Scripts/00_setup.R")
```


```{r data_prep_format setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
options(scipen=999)
```


## Formating data

We need to do some cleaning and make sure that the variables are in the right format (dates, etc.)

### Users

```{r data_prep_format loading users, echo = FALSE}
load(file = paste0(IO$output_data,"users.Rdata"), verbose = TRUE)
dim(users)
```


```{r data_prep_format cleaning users}

weight.na = which(users$weight == -999)
users$weight[weight.na] = NA
rm(weight.na)
height.na = which((users$height == -999) | (users$height > 230) | (users$height<=100))
users$height[height.na] = NA

summary(users)

```


```{r data_prep_format saving users}
save(users, file = paste0(IO$output_data,"users.Rdata"))
file.copy(paste0(IO$output_data,"users.Rdata"), paste0(IO$tmp_data,"users_after_formatting.Rdata"), overwrite = TRUE)
```


### Cycles


```{r data_prep_format loading cycles, echo = FALSE}
load(file = paste0(IO$output_data,"cycles.Rdata"), verbose = TRUE)
dim(cycles)
```

```{r data_prep_format cleaning cycles}

colnames(cycles)[which(colnames(cycles) == 'cycle_id')] = 'cycle_nb'


cycle_start_date = as.Date(cycles$cycle_start)
cycles$cycle_start = cycle_start_date
rm(cycle_start_date)

summary(cycles)

```



```{r data_prep_format saving cycles}
save(cycles, file = paste0(IO$output_data,"cycles.Rdata"))
file.copy(from = paste0(IO$output_data,"cycles.Rdata"), to = paste0(IO$tmp_data,"cycles_after_data_prep_format.Rdata"), overwrite = TRUE)

```



### Days tables


```{r data_prep_format formating days}

csv_batches_folder = paste0(IO$tmp_data,"tracking_csv_batches/")

output_days_folder = paste0(IO$output_data,"days/")
dir.create(output_days_folder)

filenames = list.files(csv_batches_folder)
load(paste0(IO$tmp_data,"tracking_colnames.Rdata"), verbose = TRUE)

cl = makeCluster(par$n_cores)
registerDoParallel(cl)

tic()
foreach(filename = filenames, .packages = "readr") %dopar%{
  cat(filename,"\n")
  days = read_csv(paste0(csv_batches_folder, filename),  progress = F, col_types = "cDccdi", col_names = FALSE)
  colnames(days) = tracking_colnames
  Rdata_filename = gsub("csv","Rdata",filename)
  save(days, file =paste0(output_days_folder, Rdata_filename))
}
toc()

stopImplicitCluster()

```


```{r data_prep_format copying days in tmp folder}

tmp_days_folder = paste0(IO$tmp_data,"days_after_data_prep_format/")
file.copy(output_days_folder, IO$tmp_data, recursive=TRUE)
file.rename(paste0(IO$tmp_data,"days"),tmp_days_folder)

```



```{r data_prep_format checking formating days}

filenames = list.files(output_days_folder)
load(file =paste0(output_days_folder, filenames[1]), verbose = TRUE)
summary(days)
```

