---
title: "Phenotyping menstrual breast tenderness from large-scale self-tracked data: data analysis"
author: "Laura Symul"
date: "last update: `r format(Sys.time(), '%d %B, %Y')`"
output: 
  bookdown::html_document2: 
    theme: flatly
    highlight: haddock
    toc: yes
    toc_float: true
    toc_depth: 5
    number_sections: true
    fig_caption: true

---

This document presents the data analyses that were performed for the manuscript "Phenotyping menstrual breast tenderness from large-scale self-tracked data" by L. Symul, P. Hillard and S Holmes.

It can be navigated using the floating table of content located on the upper left corner of this document.



```{r setup knitr, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
```

```{r setup my_scripts, include = FALSE, eval = TRUE}
source("Scripts/00_setup.R")
```

```{r setup initial initialization ^^, include = FALSE, eval = TRUE}
source("Scripts/00_init_0.R")
```



```{r child = '_intro_clue.Rmd', cache=TRUE}
```


```{r child = '_data_prep.Rmd', cache=TRUE}
```



```{r child = '_data_presentation.Rmd', cache=TRUE}
```


```{r child = '_tracking_behavior_clustering.Rmd', cache=TRUE}
```


```{r child = '_profiles.Rmd', cache=TRUE}
```

```{r child = '_cycle_prep.Rmd', cache=TRUE}
```

```{r child = '_cycle_symptoms_predictions.Rmd', cache=TRUE}
```


```{r child = '_users_description.Rmd', cache=TRUE}
```


```{r child = '_cyclicity_variability_duration_timing.Rmd', cache=TRUE}
```


```{r child = '_users_phenotyping.Rmd', cache=TRUE}
```


```{r child = '_pill_transition_analysis.Rmd', cache=TRUE}
```













