---
title: "Tender Breasts FIGURES"
author: "Laura Symul"
date: "1/16/2019"
output: 
  bookdown::html_document2: 
    theme: flatly
    highlight: haddock
    toc: yes
    toc_float: true
    toc_depth: 5
    number_sections: true
    fig_caption: true

---


```{r setup setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
```


```{r setup librairies and stuff, include = FALSE, eval = TRUE}
source("Scripts/00_setup.R")
```


```{r load users and cycles, cache = FALSE, eval = TRUE}

load(file = paste0(IO$output_data, "users.Rdata"), verbose = TRUE)
#load(file = paste0(IO$output_data, "cycles.Rdata"), verbose = TRUE)

```


# Figure 1 INTRO

## Demographics (Supplementary)


```{r data_presentation_demographics number of users in each considered category}


g = ggplot(users, aes(x = age, fill = birth_control))
g + geom_histogram(binwidth = 1) + facet_grid(birth_control ~.)

g = ggplot(users, aes(x = age, fill = country))
g + geom_histogram(binwidth = 1) + facet_wrap(country ~.)



load(file = paste0(IO$out_Rdata, "number_of_users_and_cycles_per_category.Rdata"), verbose = TRUE)


g = ggplot(agg, aes(y = birth_control, x= 0,   col = birth_control)) + 
  facet_grid(bmi_cat ~ age_cat) + 
  geom_text(aes(label = n_users)) + 
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.ticks = element_blank(),
        axis.text.x = element_blank()) + 
  guides(color = FALSE, size = FALSE) + xlab("") + ylab("") + 
  ggtitle("Number of users per category of age (horizontal) and bmi (vertical)")

g

ggsave(filename = paste0(IO$panels, "S1_X_number_of_users_per_cat.pdf"), plot = g)


g = ggplot(agg, aes(y = birth_control, x= 0,   col = birth_control)) + 
  facet_grid(bmi_cat ~ age_cat) + 
  geom_text(aes(label = n_cycles)) + 
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.ticks = element_blank(),
        axis.text.x = element_blank()) + 
  guides(color = FALSE, size = FALSE) + xlab("") + ylab("") +
  ggtitle("Number of cycles per category of age (horizontal) and bmi (vertical)")
g

ggsave(filename = paste0(IO$panels, "S1_X_number_of_cycles_per_cat.pdf"), plot = g)

```






## Examples


```{r TB examples fig 1A}

#load(paste0(IO$input_data,"days/days_1.Rdata"), verbose = TRUE)

load(file = paste0(IO$out_Rdata,"sub_days_examples_input_data.Rdata"), verbose = TRUE)
days = sub_days

user_ids = unique(days$user_id)

for(user_id in user_ids){
  j = which((days$user_id == user_id)&(!is.na(days$cycle_id_m)) & (days$category != "pill_hbc") & (days$cycle_nb_m %in% 4:8))
  d = days[j,]
  g = ggplot_user_example(d = d, title = FALSE, size_factor = 1.5)
  print(g)
  
  ggsave(filename = paste0(IO$panels, "1A_example_",d$user_id[1],".pdf"), plot = g, width = viz$full_width/2.8, height = viz$full_width/4)
  
}


```


```{r}
rm(days, user_id, user_ids, g, d, j)
```


## Tracking groups

```{r tracking groups average tracking profile, fig.width=6, fig.height=2.5}

load(file = paste0(IO$out_Rdata,"tracking_behavior_overal_pattern_by_tracking_group_and_birth_control.Rdata"), verbose = TRUE)


agg$SE = agg$fraction_cycles_with_logs_SE

g = ggplot(agg, aes(x = cycleday_m_D, y = fraction_cycles_with_logs, col = BC, shape = BC)) + 
  geom_vline(xintercept = 0, col = "gray90", size = 1.5)+
  geom_ribbon(aes(ymin = fraction_cycles_with_logs-1.96*SE, ymax = fraction_cycles_with_logs+1.96*SE, fill = BC), alpha = 0.5, col = NA)+
  geom_line() + geom_point()+ 
  scale_y_continuous(labels = scales::percent)+ scale_x_continuous(breaks = par$x.axis)+
  scale_colour_manual(values= cols$BC , name="BC")+
  scale_fill_manual(values= cols$BC , name="BC")+
  guides(col = FALSE, fill = FALSE, shape = FALSE)+
  xlab("cycleday from 1st day of menstruation") + ylab("% cycles with any log")+
  theme(legend.position="bottom",legend.background = element_rect(color="gray90", fill = NA))+
  facet_grid( . ~ tracking_group)
g


g_n = ggplot(agg, aes(x = cycleday_m_D, y = avg_n_logs, col = BC, shape = BC)) + 
  geom_vline(xintercept = 0, col = "gray90", size = 1.5)+
  geom_line() + geom_point()+ 
  scale_x_continuous(breaks = par$x.axis)+
  scale_colour_manual(values= cols$BC , name="BC")+
  scale_fill_manual(values= cols$BC , name="BC")+
  guides(col = FALSE, fill = FALSE, shape = FALSE)+
  xlab("cycleday from 1st day of menstruation") + ylab("average # of logs")+
  theme(legend.position="bottom",legend.background = element_rect(color="gray90", fill = NA))+
  facet_grid( . ~ tracking_group)
g_n


ggsave(file = paste0(IO$panels, "tracking_profile_perc_cycles_with_logs_per_tracking_group_and_BC.pdf"),
       plot = g, 
       width = viz$full_width/2,
       height = 0.3*viz$full_width/2,
       scale = viz$scale)

ggsave(file = paste0(IO$panels, "tracking_profile_avg_log_per_tracking_group_and_BC.pdf"),
       plot = g_n, 
       width = viz$full_width/2,
       height = 0.3*viz$full_width/2,
       scale = viz$scale)


```


##  Overall tender breasts profiles per tracking groups

```{r tracking groups average symptoms profile, fig.width=6, fig.height=2.5}

load(file = paste0(IO$out_Rdata,"TB_overal_pattern_by_tracking_group_and_birth_control.Rdata"), verbose = TRUE)


agg$SE = agg$fraction_cycles_with_TB_SE

g = ggplot(agg, aes(x = cycleday_m_D, y = fraction_cycles_with_TB, col = BC, shape = BC)) + 
  geom_vline(xintercept = 0, col = "gray90", size = 1.5)+
  geom_ribbon(aes(ymin = fraction_cycles_with_TB-1.96*SE, ymax = fraction_cycles_with_TB+1.96*SE, fill = BC), alpha = 0.5, col = NA)+
  geom_line() + geom_point()+ 
  scale_y_continuous(labels = scales::percent)+ scale_x_continuous(breaks = par$x.axis)+
  scale_colour_manual(values= cols$BC , name="BC")+
  scale_fill_manual(values= cols$BC , name="BC")+
  guides(col = FALSE, fill = FALSE, shape = FALSE)+
  xlab("cycleday from 1st day of menstruation") + ylab("% cycles with reported BT")+
  theme(legend.position="bottom",legend.background = element_rect(color="gray90", fill = NA))+
  facet_grid( . ~ tracking_group)
g


ggsave(file = paste0(IO$panels, "symptoms_profile_per_tracking_group_and_BC.pdf"),
       plot = g, 
       width = viz$full_width/2,
       height = 0.3*viz$full_width/2,
       scale = viz$scale)


```


## Overall tender breasts profiles per age categories and BC for cycles with regular tracking

```{r overall_profile profile by BC and age cat}

load(file = paste0(IO$out_Rdata,"TB_overal_pattern_by_age_cat_and_birth_control_for_regular_tracking.Rdata"), verbose = TRUE)

agg$age_x_BC = interaction(agg$age_cat , agg$BC)
agg$SE = agg$fraction_cycles_with_TB_SE


j = which(agg$age_cat %in% par$age_cat_exclude)
if(length(j)>0){agg = agg[-j,]}
j = which((agg$age_cat == "(35,40]") & (agg$BC == "pill"))
if(length(j)>0){agg = agg[-j,]}

agg = agg[which(agg$tracking_group == "regular tracking"),]

g = ggplot(agg, aes(x = cycleday_m_D, y = fraction_cycles_with_TB, col = age_x_BC, shape = BC)) + 
  geom_vline(xintercept = 0, col = "gray90", size = 1.5)+
  geom_ribbon(aes(ymin = fraction_cycles_with_TB-1.96*SE, ymax = fraction_cycles_with_TB+1.96*SE, fill = age_x_BC), alpha = 0.5, col = NA)+
  geom_line() + geom_point()+ 
  scale_y_continuous(labels = scales::percent)+ scale_x_continuous(breaks = par$x.axis)+
  scale_colour_manual(values= cols$age_x_BC , name="Age group x BC")+
  scale_fill_manual(values= cols$age_x_BC , name="Age group x BC")+
  guides(col = FALSE, fill = FALSE, shape = FALSE)+
  xlab("cycleday from 1st day of menstruation") + ylab("% cycles with reported TB")+
  theme(legend.position="bottom",legend.background = element_rect(color="gray90", fill = NA))#+
#facet_grid(. ~ tracking_group)
g

ggsave(filename = paste0(IO$panels, "symptoms_profile_by_BC_and_age_cat_for_regular_tracking.pdf"), 
       plot = g, 
       width = viz$full_width/2, 
       height = 0.5*viz$full_width/2,
       scale = viz$scale)


```





```{r fraction of symptoms per cycle per users}
load(file = paste0(IO$out_Rdata, "avg_symptoms_per_user.Rdata"), verbose = TRUE)


g = ggplot(agg[agg$BC %in% c("pill","none / condoms"),], aes(x = n_TB_by_n_cycles, y = perc_users, fill = BC)) +
  geom_bar(stat = "identity", position = "dodge" )+
  scale_fill_manual(values = cols$BC)+
  xlab("# of reported TB symptoms / # of cycles")+ 
  ylab("% of users") + guides(fill = FALSE)
g


ggsave(filename = paste0(IO$panels, "1_avg_TB_per_user.pdf"), plot = g, width = viz$full_width/4.5, height = viz$full_width/4.5, scale = viz$scale)


```


```{r Number of TB per cycle}

load(file = paste0(IO$out_Rdata, "n_TB_per_cycle.Rdata"), verbose=TRUE)

g = ggplot(agg[agg$BC != "unclear",], aes(x = tender_breasts_ul, y = perc_cycles, fill = BC)) +
  geom_bar(stat = "identity", position = "dodge") + 
  scale_fill_manual(values = cols$BC3) + guides(fill = FALSE)+
  xlab("# of reported Tender Breast symptoms per cycle")+ ylab("% of cycles")

g

ggsave(filename = paste0(IO$panels, "1_number_of_TB_per_cycle.pdf"), plot = g, width = viz$full_width/4, height = viz$full_width/4.5, scale = viz$scale)




```




# Evolution in time

```{r evolution in time}

load(file = paste0(IO$out_Rdata,"evolution_of_symptom_tracking_in_time.Rdata"), verbose = TRUE)
load(file = paste0(IO$out_Rdata,"evolution_of_symptom_tracking_in_time_min_n_cycles.Rdata"), verbose = TRUE)

fraction_TB$init_TB_group_text = factor(paste0("avg. #BT in cycles 1-5 = ",fraction_TB$init_TB_group))
min_n_cycles$init_TB_group_text = factor(paste0("avg. #BT in cycles 1-5 = ",min_n_cycles$init_TB_group))

fraction_TB$BC_x_init_TB_group =  interaction(fraction_TB$init_TB_group, fraction_TB$BC)
min_n_cycles$BC_x_init_TB_group =  interaction(min_n_cycles$init_TB_group, min_n_cycles$BC)


g = ggplot(fraction_TB, aes(x = cycle_nb_m_rel, y = median_n_TB, col = BC_x_init_TB_group, fill = BC_x_init_TB_group)) + 
  geom_line() + 
  geom_line(aes(y = avg_n_TB), linetype = 3) + 
  geom_ribbon(aes(ymin = q_05_n_TB , ymax = q_95_n_TB), alpha = 0.2, col = NA)+
  geom_ribbon(aes(ymin = q_25_n_TB , ymax = q_75_n_TB), alpha = 0.2, col = NA)+
  geom_text(data = min_n_cycles, aes(label = paste0("min # = ",min_n_cycles)), x = 0.5, y = 0.95*max(fraction_TB$q_95_n_TB), size = 3, vjust = 0, hjust = 0)+
  facet_grid(BC  ~ init_TB_group_text )+
  scale_y_continuous(breaks = seq(0,21, by = 3), minor_breaks = 0:21)+
  scale_color_manual(values = cols$BC_x_init_TB_group) + scale_fill_manual(values = cols$BC_x_init_TB_group)+ 
  guides(col = FALSE, fill = FALSE) +
  xlab("Cycle number") + ylab("# of reported BT")
g


ggsave(filename = paste0(IO$panels, "evolution_in_time.pdf"), 
       plot = g, 
       width = viz$full_width/2, 
       height = 0.5*viz$full_width/2,
       scale = viz$scale)


```



# Consistency of Symptoms

```{r consistency of symptoms - all examples, fig.width= 12, fig.height=10 }

load(file = paste0(IO$out_Rdata,"consistent_and_inconsistent_users.Rdata"), verbose = TRUE)


sel_d_consistent = sel_d[sel_d$consistent == "consistent", ]
sel_d_average = sel_d[sel_d$consistent == "average", ]
sel_d_inconsistent = sel_d[sel_d$consistent == "inconsistent", ]


if((nrow(sel_d_inconsistent)>0)&(nrow(sel_d_consistent)>0)){
  
  g_consistent = ggplot_imputed_TB(sel_d = sel_d_consistent, 
                                   facet_grid = c("BC","init_TB_group","user_id"), cycle_id = FALSE, col = "user_id")
  
  
  g_average = ggplot_imputed_TB(sel_d = sel_d_average, 
                                facet_grid = c("BC","init_TB_group","user_id"), cycle_id = FALSE, col = "user_id")
  
  
  
  g_inconsistent = ggplot_imputed_TB(sel_d = sel_d_inconsistent, 
                                     facet_grid = c("BC","init_TB_group","user_id"), cycle_id = FALSE, col = "user_id")
  
  grid.arrange(g_inconsistent, g_average, g_consistent, nrow = 1)
}

```



```{r consistency of symptoms - specific examples, fig.width= 12, fig.height=5 }

load(file = paste0(IO$out_Rdata,"consistent_and_inconsistent_users.Rdata"), verbose = TRUE)

user_ids = 
  c("586e33d674b46555254e908ec42d6771ed294bcd", "ff484ef33fd2c29086617ed63a9814571b86f15d", 
    "677332825213f1f0cb1e6831ead1fc787cf01663", "8714aad3100409673b8762775e474aff17321df4", 
    "40620830924a2f02935e3a6c6102f84e5de35fce","6ef947aeb9cfe0468bd1efd26b8a10dca0a1e645")

sel_d = sel_d[which(sel_d$user_id %in% user_ids),]

sel_d_consistent = sel_d[sel_d$consistent == "consistent", ]
sel_d_average = sel_d[sel_d$consistent == "average", ]
sel_d_inconsistent = sel_d[sel_d$consistent == "inconsistent", ]

if((nrow(sel_d_inconsistent)>0)&(nrow(sel_d_consistent)>0)&(nrow(sel_d_average)>0)){
  
  g_consistent = ggplot_imputed_TB(sel_d = sel_d_consistent, 
                                   facet_grid = c("BC"), cycle_id = FALSE, col = "BC")+
    scale_color_manual(values = cols$BC)+ylab("")+theme(strip.text = element_blank())
  
  g_average = ggplot_imputed_TB(sel_d = sel_d_average, 
                                facet_grid = c("BC"), cycle_id = FALSE, col = "BC")+
    scale_color_manual(values = cols$BC)+ylab("")+theme(strip.text = element_blank())
  
  
  g_inconsistent = ggplot_imputed_TB(sel_d = sel_d_inconsistent, 
                                     facet_grid = c("BC"), cycle_id = FALSE, col = "BC")+
    scale_color_manual(values = cols$BC)+ylab("")+theme(strip.text = element_blank())
  
  
  grid.arrange(g_inconsistent, g_average, g_consistent, nrow = 1)
  g_consistency = arrangeGrob(g_inconsistent, g_average, g_consistent, nrow = 1, widths = c(1,1,1))
  g_consistency
  
  ggsave(filename = paste0(IO$panels, "consistency_examples.pdf"), 
         plot = g_consistency, 
         width = viz$full_width/2, 
         height = 0.33*viz$full_width/2,
         scale = viz$scale*1.7)
  
  
}




```



```{r consistency}
load(file = paste0(IO$out_Rdata,"consistency_summary.Rdata"), verbose = TRUE)

df$BC = factor(df$BC, levels = c(as.character(par$BC_dict$name),"both"))
df$BC_x_init_TB_group =  interaction(df$init_TB_group, df$BC)


g = ggplot(df, aes(x = consistency, y = n_users, fill = BC_x_init_TB_group)) + 
  geom_area(position = "identity", alpha = 0.75) + 
  facet_grid(BC ~ . , scale = "free_y")+
  scale_fill_manual(values = cols$BC_x_init_TB_group2)+
  guides(fill = FALSE)
g


ggsave(filename = paste0(IO$panels, "consistency_summary.pdf"), 
       plot = g, 
       width = viz$full_width/2.5, 
       height = 0.6*viz$full_width/2.5,
       scale = viz$scale)

```





# Phenotyping


```{r phenotyping}

for(bc in c("NC","pill")){
  i = (bc == "pill")+1
  BC = par$BC_dict$name[i]
  load(file = paste0(IO$tmp_data,"user_phenotyping_",bc,".Rdata"), verbose = TRUE)
  
  # screeplot
  eig_df = data.frame(x = 1:10, eig = mds$eig[1:10])
  g = ggplot(eig_df, aes(x = x, y = eig)) + geom_bar(stat = "identity", fill = cols$BC[i])
  g
  
  ggsave(filename = paste0(IO$panels, "S_screeplot_",bc,".pdf"), 
         plot = g, 
         width = viz$full_width/3, 
         height = 0.75*viz$full_width/3,
         scale = viz$scale)
  
  
  # interactive 3D
  
  plot_ly(mds_df, x = ~X1, y = ~X2, z = ~X3,
          color = ~n_days,
          type = "scatter3d", mode = "markers",
          marker = list(size = 4),
          text = ~paste('ID: ', user_id))
  
  
  plot_ly(mds_df, x = ~X1, y = ~X2, z = ~X3,
          color = ~time,
          type = "scatter3d", mode = "markers",
          marker = list(size = 4),
          text = ~paste('ID: ', user_id))
  
  
  plot_ly(mds_df, x = ~X1, y = ~X2, z = ~X3,
          color = ~max,
          type = "scatter3d", mode = "markers",
          marker = list(size = 4),
          text = ~paste('ID: ', user_id))
  
  plot_ly(mds_df, x = ~X1, y = ~X2, z = ~X3,
          color = ~time_last_symptoms,
          type = "scatter3d", mode = "markers",
          marker = list(size = 4),
          text = ~paste('ID: ', user_id))
  
  # interactive 2D
  
  
  plot_ly(mds_df, x = ~X1, y = ~X2,
          color = ~X3,
          type = "scatter", mode = "markers",
          marker = list(size = 4),
          text = ~paste('ID: ', user_id))
  
  plot_ly(mds_df, x = ~X1, y = ~X3,
          color = ~X2,
          type = "scatter", mode = "markers",
          marker = list(size = 4),
          text = ~paste('ID: ', user_id))
  
  
  
  
  if(bc == "pill"){
    #mds_df$user_id[grep("65035d",mds_df$user_id)]
    user_ids = c("0ceafb77c214fb6e45d069e6c645083a9f7799d0","d0fcb8602f237946a56162f047c8ef3ef254541c",special_pill_user,
                 "73266275a3d6f3898cf58269070edb4d4edd2034","e610274623760e9c4f1a50e0ed5a00f17117ed0b",
                 "65035d05a6ccabaaeb82ecd4e17bde1c096adc2f",
                 "c45cd0e050cf6d704da32cbab899bacf51a519a3")
  }else{
    user_ids = c("2ac70e8def770369d086e9249fee9d5b3485ad0d","cb2700ea5a33499b1c97113444e1b2e5d0d09162",
                 "c4bf18fef2f8db48d6f4a881b1a23be849cbbc06","b70dde8d03e0f39bdb4cb67c88b0d26ad6002bd1",
                 "2eedf35808effb0a40381e11d1c94257096ab8de","cffcd394d8f769d363f67eada7f16b0106c3191a",
                 "b9590a55307d916d4aabc8e386bc76586a28ae0b")
    
    user_ids = c("2ac70e8def770369d086e9249fee9d5b3485ad0d","cb2700ea5a33499b1c97113444e1b2e5d0d09162",
                 "cffcd394d8f769d363f67eada7f16b0106c3191a","b70dde8d03e0f39bdb4cb67c88b0d26ad6002bd1",
                 "c4bf18fef2f8db48d6f4a881b1a23be849cbbc06","34c8890de2da03e29a7f93771ea9ecaf12cf4c88",
                 "2eedf35808effb0a40381e11d1c94257096ab8de")
  }
  
  j_mds = which(mds_df$user_id %in% user_ids)
  mds_df_subset = mds_df[j_mds,]
  mds_df_subset$user_id = factor(as.character(mds_df_subset$user_id), levels = user_ids)
  
  # MDS
  g_12 = ggplot(mds_df, aes(x = X1, y = X2)) + coord_fixed()+
    geom_point(alpha = 0.5, size = 0.3, col = "gray40")+
    geom_point(data = mds_df_subset, aes(x = X1, y = X2, col = user_id), size = 2, alpha = 0.7)+
    guides(col = FALSE)
  
  g_13 = ggplot(mds_df, aes(x = X1, y = X3)) + coord_fixed()+
    geom_point(alpha = 0.5, size = 0.3, col = "gray40") +
    geom_point(data = mds_df_subset, aes(x = X1, y = X3, col = user_id), size = 2, alpha = 0.7)+
    guides(col = FALSE)
  
  grid.arrange(g_12, g_13, nrow = 1)
  g_mds = arrangeGrob(g_12, g_13, nrow = 1)
  g_mds
  
  ggsave(filename = paste0(IO$panels, "mds_",bc,".pdf"), 
         plot = g_mds, 
         width = viz$full_width/2, 
         height = 0.5*viz$full_width/2,
         scale = viz$scale)
  
  
  avg_profiles = this_avg_profile_per_user[which(this_avg_profile_per_user$user_id %in%  user_ids),]
  
  c_wide_subset = this_c_wide[which(this_c_wide$user_id %in%  user_ids),]
  avg_profiles = melt(c_wide_subset)
  avg_profiles$avg_tender_breast = avg_profiles$value
  avg_profiles$user_id = factor(as.character(avg_profiles$user_id), levels = user_ids)
  
  g_profiles = ggplot(avg_profiles, aes(x = cycleday_m_D, y = avg_tender_breast, fill = user_id, col = user_id))+
    #geom_point()+
    #geom_line()+
    geom_area(position = "identity", alpha = 0.75)+
    facet_grid(user_id ~ .)+
    guides(col = FALSE, fill = FALSE)+
    theme(strip.text = element_blank())+
    scale_y_continuous(breaks = c(0,0.5,1))+
    scale_x_continuous(breaks = par$x.axis)
  g_profiles
  
  ggsave(filename = paste0(IO$panels, "profiles_",bc,".pdf"), 
         plot = g_profiles, 
         width = viz$full_width/4, 
         height = 0.65*viz$full_width/4,
         scale = viz$scale*1.5)
  
}


```













# Figure 3 PILL TRANSITION


```{r}



load(file = paste0(IO$out_Rdata,"pill_transition_profiles.Rdata"), verbose = TRUE)

transition_profiles$TB_change_cat_simple = factor(transition_profiles$TB_change_cat_simple  , levels = c("increase","no change","decrease"))

agg = unique(transition_profiles[,c("TB_change_cat_simple","transition","n_users")])
agg$cycle_nb_m_from_trans = -4
agg

agg_sum = aggregate( n_users ~ transition, agg, FUN = sum )
colnames(agg_sum) = c("transition","n_users_tot")
agg = merge(agg, agg_sum, all = TRUE)
agg$perc_users = paste0(round(100*agg$n_users/agg$n_users_tot),"%")
agg$text = paste0(agg$n_users, "\n",agg$perc_users)

g = ggplot(transition_profiles, aes(x = cycleday_m_D, y = fraction_cycles_with_TB, col = BC)) + 
  geom_line()+ facet_grid(transition + TB_change_cat_simple ~ cycle_nb_m_from_trans) +
  scale_x_continuous(breaks = par$x.axis, limits = c(-par$D,par$Df))+ guides(col = FALSE)+
  geom_text(data = agg, aes(x = -par$D, y = 0.5*max(transition_profiles$fraction_cycles_with_TB), col = transition, label = text), 
            nudge_x = 7, nudge_y = 0, size = 3.5)+
  scale_color_manual(values = rep(cols$BC,2))
print(g)


ggsave(filename = paste0(IO$panels, "profiles_pill_transition.pdf"), 
       plot = g, 
       width = viz$full_width/2, 
       height = 0.75*viz$full_width/2,
       scale = viz$scale)




```


