---
title: "Infering TB from missing data"
author: "Laura Symul"
date: "11/26/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
```



```{r librairies and stuff, include = FALSE, eval = TRUE}
source("00_variables.R")
source("00_libraries.R")
source("00_functions.R")
```


```{r ggplot setup}
theme_set(theme_minimal())
```


```{r parameters, include=FALSE}
par = list()
par$reset = FALSE
par$N.files = 1
par$n_cores = detectCores() - 1
```


# Loading data


We take all **unique** logs from users that are on "none" or "condoms" or "pill" as birth control method (on-boarding data)

```{r birth control parameters}
par$selected_birth_control = c("none","condoms", "pill")
par$birth_control = c("none / condoms", "pill")
```


```{r loading data, eval = FALSE}

days_folder = paste0(IO$Rdata,"days_selected_logs_witn_log_counts/")
if(!dir.exists(days_folder)){dir.create(days_folder)}


clue_file_list = list.files(IO$clue_data_path_days)
clue_file_list = clue_file_list[1:par$N.files]

registerDoParallel(par$n_cores)

tic()
foreach(file = clue_file_list) %dopar%
{
  cat(file,"\n")
  load(paste0(IO$clue_data_path_days, file), verbose = TRUE)
  days$cycle_id = as.character(days$cycle_id)
  row.keep = (days$birth_control %in% par$selected_birth_control ) &
    ( (days$category == "period") | (days$category == "pill_hbc") | (days$type == "tender_breasts") )
  
  # counting the number of log each day
  tic()
  agg = aggregate(type ~ user_id + cycle_id + cycleday, days, lu)
  toc()
  colnames(agg)[which(colnames(agg) == "type")] = "n_logs"
  
  days =  days[which(row.keep), ]
  days = merge(days, agg, all = TRUE)
  
  
  days$birth_control_o = factor(days$birth_control, levels = par$selected_birth_control)
  days$birth_control = as.character(days$birth_control)
  days$birth_control[days$birth_control %in% c("none","condoms")] = par$birth_control[1]
  days$birth_control = factor(days$birth_control, levels = par$birth_control)
  days$country = as.character(days$country)
  save(days, file = paste0(days_folder,file))
  rm(row.keep, days)
}
toc()
stopImplicitCluster()
rm(clue_file_list, days_folders)


```




```{r when TB has been tracked the value is 1 else 0}

days$number_TB = 0
days$number_TB[days$type == "tender_breasts"] = 1


```



```{r we need to define a day_id to match the n_logs}
days$day_id = paste0(days$user_id, "_", days$date)

```



```{r finding the holes in tender_breasts tracking}

d = days[days$type == "tender_breasts",]
d = d[order(d$user_id, d$cycle_id, d$cycleday),]

lag_tracking = diff(d$date)


# holes
j = which(lag_tracking == 2)


d$hole = NA
d$hole[j] = "before hole"
d$hole[j+1]  = "after hole"

jj = sort(c(j, j+1))
head(d[jj,])


```


```{r  creating the new rows for the new tender_breasts values}

# dd are the new rows that need to be added to days

dd = d[j,]
dd$hole = "hole"
dd$date = dd$date+1
dd$number_TB = 0
dd$cycleday = dd$cycleday+1
dd$cycleday_from_end = dd$cycleday_from_end + 1
dd$day_id =  paste0(dd$user_id, "_", dd$date)

k = match(dd$day_id, days$day_id)
dd$n_logs = days$n_logs[k]
dd$n_logs[is.na(dd$n_logs)] = 0

# we need to fix the days that were are the end of cycles  
k = which(dd$cycleday > dd$cycle_length)
dd$cycleday[k] = 1
dd$cycle_nb[k] = dd$cycle_nb[k]+1
dd$cycle_id = paste0(dd$user_id, "_",dd$cycle_nb)
# from here I can match with the new cycle_id
m = match(dd$cycle_id[k], days$cycle_id)
dd$cycle_start[k] = days$cycle_start[m]
dd$cycle_end[k] = days$cycle_end[m]
dd$cycle_length[k] = days$cycle_length[m]
dd$period_length[k] = days$period_length[m]
dd$is_first_cycle[k] = days$is_first_cycle[m]
dd$is_last_cycle[k] = days$is_last_cycle[m]

dd$cycleday_from_end[k] = as.numeric(dd$cycle_end[k] - dd$date[k]) - 1


rm(k, m)

```


```{r computing the new values for the new rows}

ddd = rbind(d[jj,],dd)
ddd = ddd[order(ddd$user_id, ddd$date),]

k = which(ddd$hole == "hole")
mean_n_logs = (ddd$n_logs[k-1] + ddd$n_logs[k+1])/2
ddd$number_TB[k] = 0.75*(mean_n_logs - pmin(ddd$n_logs[k], mean_n_logs))/mean_n_logs


rm(k, mean_n_logs)

```

```{r adding the new rows to days}

days$original = TRUE
k = which(ddd$hole == "hole")
ddd$original = TRUE; ddd$original[k] = FALSE
days = rbind(days, ddd[k,-which(colnames(ddd) == "hole")])
rm(k)

```



```{r plot a few examples}

user_ids = unique(days$user_id[which(days$number_TB == 0.5)])[11:20]

user_ids = c("004e472991e8c87c0caf919f191c7903329f87cb","027b96a3e5640cb66014f4c269c1d2cd202bc80e","030f52cc736c94780282917db5fc6ca8f91d86a4","0560c1610a3c7375ef24cca805929192c6f809fb")

for(user_id in user_ids){
  cat(user_id,"\n")
  k = which((days$user_id == user_id)&(!is.na(days$cycle_nb)))
  days_this_user = days[k,]
  
  days_this_user[,c("user_id","cycle_nb","cycleday","category","type","number_TB","n_logs")]
  
  # g = ggplot(days_this_user, aes(x = cycleday_from_end, y = -n_logs))+ 
  #   geom_bar(stat = "identity") + geom_point(aes(y = 10, alpha = number_TB))+
  #   facet_grid(cycle_nb~.)
  #g
  
  # first only plot the original data
  g = ggplot(days_this_user[days_this_user$original,], aes(x = cycleday, y = n_logs))+ 
    geom_bar(stat = "identity") + geom_point(aes(y = -20, alpha = number_TB, shape = original), col = "steelblue")+
    facet_grid(cycle_nb~.) + scale_alpha(range = c(0, 1)) + ggtitle(user_id)
  print(g)
  
  ggsave(filename = paste0("plots/",user_id,"_only_original_data.pdf"), plot = g)
  
  # then add the imputed data
  g = ggplot(days_this_user, aes(x = cycleday, y = n_logs))+ 
    geom_bar(stat = "identity") + geom_point(aes(y = -20, alpha = number_TB, shape = original), col = "steelblue")+
    facet_grid(cycle_nb~.) + scale_alpha(range = c(0, 1)) + ggtitle(user_id)
  print(g)
  
  ggsave(filename = paste0("plots/",user_id,"_with_inferred_data.pdf"), plot = g)
  
  
  
}

```




```{r trash}
tic()
agg = aggregate(days$type, by = days[, -c(which(colnames(days) %in% c("category","type","number")))], lu)
toc()
```





