---
title: "Pill transition"
author: "Laura Symul"
date: "12/7/2018"
output: html_document
---




# No pill > pill TRANSITION - Figure 3


The pre-processing of the data to find which users were initially not taking the pill and have started to take the pill has been done in the file `00_finding_users_who_started_taking_the_pill.Rmd`.


```{r pill_perturbation_analysis load cycles with bc changes}
load( file = paste0(IO$Rdata,"cycles_bc_change.Rdata"), verbose = TRUE)
```


```{r pill_perturbation_analysis pull out the days for these users}

days_folder = paste0(IO$Rdata, "days/")
days_files = list.files(path = days_folder)

days_bc_change = data.frame()
tic()
for(filename in days_files){
  cat(filename, "\n")
  load(paste0(days_folder, filename), verbose = TRUE)
  j = which(days$cycle_id %in% cycles_bc_change$cycle_id)
  days_bc_change = rbind(days_bc_change, days[j,])
  rm(j, days)
}
toc()

days = days_bc_change
save(days, file = paste0(IO$Rdata,"days_bc_change.Rdata"))
rm(days_folder, days_files, days_bc_change)
```


```{r pill_perturbation_analysis adding pill status to days}

days$pill_status = cycles_bc_change$pill_status[match(days$cycle_id, cycles_bc_change$cycle_id)]

```

```{r pill_perturbation_analysis defining a day since pill start}

agg = aggregate(date ~ user_id, days[days$pill_status == "on_the_pill",], min )
days_date_pill_transition = agg$date[match(days$user_id, agg$user_id)]
days$day_since_pill_transition = as.numeric(days$date - days_date_pill_transition)

rm(agg, days_date_pill_transition)

```


```{r pill_perturbation_analysis defining a cycle number since pill start}

agg = aggregate(cycle_nb_m ~ user_id, days[days$pill_status == "on_the_pill",], min )
cycles_pill_transition = agg$cycle_nb_m[match(days$user_id, agg$user_id)]
days$cycle_nb_from_pill = days$cycle_nb_m - cycles_pill_transition

rm(agg, cycles_pill_transition)

```




## Looking at a few examples



```{r pill_perturbation_analysis factorizing types and categories to order the plots}
days$type_o = days$type
days$type = factor(days$type, levels = c( "late"    ,  "missed"  , "double"  , "taken" ,"heavy","medium", "light"  , "spotting" ,"tender_breasts", ""))
```



```{r pill_perturbation_analysis showing a few examples of users who started to take the pill}
set.seed(1)
user_ids = unique(cycles_bc_change$user_id)
user_ids = user_ids[sample(1:length(user_ids),10)]

for(user_id in user_ids){
  this.user.days = days[which(days$user_id == user_id),]
  print(ggplot(this.user.days, aes(x = date, y = type, col = category)) + geom_vline(xintercept = this.user.days$date[this.user.days$cycleday == 1], col = "gray70") + geom_point(size = 0.7) )
}

```

```{r pill_perturbation_analysis showing examples - prep Figure 3A}

agg_c = aggregate( type ~ user_id + cycle_id + pill_status, days[days$type == TB, ], length)
colnames(agg_c)[colnames(agg_c) == "type"] = "n_tender_breasts"

agg_u = aggregate(n_tender_breasts ~ user_id + pill_status, agg_c, sum)
agg_n = aggregate(cycle_id ~ user_id + pill_status, agg_c, lu)
colnames(agg_n)[colnames(agg_n) == "cycle_id"] = "n_cycles"
agg_u = merge(agg_u, agg_n, all = TRUE)
agg_u$avg_tender_breasts_per_cycle = agg_u$n_tender_breasts/agg_u$n_cycles

agg_u_wide = reshape(agg_u[, c("user_id","pill_status","avg_tender_breasts_per_cycle")],idvar = "user_id", timevar = "pill_status", direction = "wide")
agg_u_wide[is.na(agg_u_wide)] = 0
agg_u_wide$avg_tender_breasts_change =  agg_u_wide$avg_tender_breasts_per_cycle.on_the_pill - agg_u_wide$avg_tender_breasts_per_cycle.before_the_pill

ggplot(agg_u_wide, aes(x = avg_tender_breasts_per_cycle.before_the_pill, y = avg_tender_breasts_per_cycle.on_the_pill)) + geom_point(alpha = 0.1)

ggplot(agg_u_wide, aes(x = avg_tender_breasts_change)) + geom_histogram(binwidth = 1)


rm(agg_c, agg_u,agg_n)
```



```{r pill_perturbation_analysis showing examples - pre-selection - Figure 3A}


k = which(round(abs(agg_u_wide$avg_tender_breasts_change)) == 5 )
user_ids = agg_u_wide$user_id[k]

j = which(days$user_id %in% user_ids)
d = days[j,]
d$user_id = factor(d$user_id, levels = user_ids)

ggplot(d, aes(x = day_since_pill_transition, y = category, col = type)) + geom_point(size = 0.5) + facet_grid(user_id ~ . ) 


user_ids = user_ids[c(6, 20)]

j = which(days$user_id %in% user_ids)
d = days[j,]
d$user_id = factor(d$user_id, levels = user_ids)
ggplot(d, aes(x = day_since_pill_transition, y = category, col = type)) + geom_point(size = 0.5) + facet_grid(user_id ~ . ) + xlim(c(-350,200))



rm(k, j, d)
```


```{r pill_perturbation_analysis showing examples - Figure 3A}

j = which(days$user_id %in% user_ids)
d = days[j,]
d$user_id = factor(d$user_id, levels = user_ids)


d$user_id = c("user 1","user 2")[as.numeric(d$user_id)]
d$category[d$category == "pain"] = TB
d$category[d$category == "pill_hbc"] = "pill"
d$category = factor(d$category, levels = c("period" ,TB,"pill"))
d$type = factor(d$type, levels = c("taken","missed","double","late","spotting","light","medium","heavy","tender_breasts"))
d$number = 0.75
d$number[d$category == "pill"] = 0.5
d$number[d$type == "spotting"] = 0.5
d$number[d$type == "light"] = 1
d$number[d$type == "medium"] = 2
d$number[d$type == "heavy"] = 3

g = ggplot(d, aes(x = day_since_pill_transition, y = category, col = type, shape = category, size = number)) + 
  geom_point( shape = "|") + scale_size(range=c(4,6))+
  facet_grid(user_id ~ . ) + 
  scale_x_continuous(breaks = seq(-360,150, by = 90), 
                     minor_breaks =  seq(-330,150, by = 30), 
                     limits = c(-330,150), expand = c(0,0))+
  scale_color_manual(name = "", 
                     values = c("skyblue3","red","mediumpurple4","orange","tomato1","tomato2","tomato3","tomato4","skyblue"))+
  xlab("Days since 1st cycle taking the pill")+ ylab("")+
  theme( legend.margin = margin(0,0,0,0),
        legend.key.size = unit(0.35,'cm'),
        legend.key.height = unit(0.35, 'cm'))+ 
  #legend.position="bottom", legend.background = element_rect(color="gray90", size=.5, linetype = 1),
  guides(shape = FALSE, size = FALSE)#, color = FALSE)
g

ggsave(filename = paste0(IO$panels, "3A_pill_transition_examples.pdf"), plot = g, width = viz$full_width, height = viz$full_width/6)



rm(k, j, d)
```



## Overall trend

```{r pill_perturbation_analysis pill transition overall trend}
agg = aggregate(type ~ cycleday_m_D + pill_status , days[(!is.na(days$pill_status)) & (days$type == "tender_breasts"),], length)
colnames(agg)[colnames(agg) == "type"] = "n_tender_breasts"
```


```{r pill_perturbation_analysis pill transition overall trend viz}

ggplot(agg, aes(x = cycleday_m_D, y = n_tender_breasts, col = pill_status)) + geom_line()

agg_n = aggregate(cycle_id ~ pill_status, days[(!is.na(days$pill_status)),], lu )
colnames(agg_n)[colnames(agg_n) == "cycle_id"] = "n_cycles"

agg = merge(agg, agg_n, all = TRUE)

agg$perc_tender_breasts = agg$n_tender_breasts/agg$n_cycles

ggplot(agg, aes(x = cycleday_m_D, y = perc_tender_breasts, col = pill_status)) + geom_line() + scale_y_continuous(labels=percent)


```




## Overall trend in time



```{r pill_perturbation_analysis pill transition overall trend in time}

agg = aggregate(type ~ cycleday_m_D + pill_status + cycle_nb_from_pill, days[(days$type == "tender_breasts"),], length)
colnames(agg)[colnames(agg) == "type"] = "n_tender_breasts"

#ggplot(agg[agg$cycle_nb_from_pill %in% c(-7:7),], aes(x = cycleday_m_D, y = n_tender_breasts, col = pill_status)) + geom_line() + facet_grid(.~cycle_nb_from_pill)

agg_n = aggregate(cycle_id_m ~ cycle_nb_from_pill, days, lu )
colnames(agg_n)[colnames(agg_n) == "cycle_id_m"] = "n_cycles"

agg = merge(agg, agg_n, all = TRUE)

agg$perc_tender_breasts = agg$n_tender_breasts/agg$n_cycles

g = ggplot(agg[agg$cycle_nb_from_pill %in% c(-7:7),], aes(x = cycleday_m_D, y = perc_tender_breasts, col = pill_status))+ 
  geom_vline(xintercept = 0, col = "gray80") + 
  geom_line()+ facet_grid(.~cycle_nb_from_pill)+ 
  scale_x_continuous(breaks = c(-14,0), minor_breaks = par$x.axis)+
  scale_y_continuous(labels = scales::percent)+
  xlab("cycleday from menstruation")+
  ylab("% of reported breasts tenderness")+
  scale_color_manual(values = cols$pill_trans)+
  guides(color = FALSE) 
g

ggsave(filename = paste0(IO$panels, "3B_pill_transition_overall.pdf"), plot = g, width = viz$full_width/2*viz$scale, height = viz$full_width/5*viz$scale)

 


```




```{r pill_perturbation_analysis pill transition overall trend in time increase vs decrease}

agg_u_wide$increase = agg_u_wide$avg_tender_breasts_change>0
agg_u_wide$symptoms_change =  c("decreased\nsymptoms", "increased\nsymptoms")[agg_u_wide$increase+1]

days$pill_TB_increase = agg_u_wide$increase[match(days$user_id, agg_u_wide$user_id)]
days$symptoms_change = c("decreased\nsymptoms", "increased\nsymptoms")[days$pill_TB_increase+1]

agg = aggregate(type ~ cycleday_m_D + pill_status + cycle_nb_from_pill + symptoms_change, days[(days$type == "tender_breasts"),], length)
colnames(agg)[colnames(agg) == "type"] = "n_tender_breasts"

#ggplot(agg[agg$cycle_nb_from_pill %in% c(-7:7),], aes(x = cycleday_m_D, y = n_tender_breasts, col = pill_status)) + geom_line() + facet_grid(.~cycle_nb_from_pill)

agg_n = aggregate(cycle_id_m ~ cycle_nb_from_pill + symptoms_change, days, lu )
colnames(agg_n)[colnames(agg_n) == "cycle_id_m"] = "n_cycles"

agg = merge(agg, agg_n, all = TRUE)

agg$perc_tender_breasts = agg$n_tender_breasts/agg$n_cycles

g = ggplot(agg[agg$cycle_nb_from_pill %in% c(-7:7),], aes(x = cycleday_m_D, y = perc_tender_breasts, col = pill_status))+ 
  geom_vline(xintercept = 0, col = "gray80") + 
  geom_line()+ facet_grid(symptoms_change~cycle_nb_from_pill)+ 
  scale_x_continuous(breaks = c(-14,0), minor_breaks = par$x.axis)+
  scale_y_continuous(labels = scales::percent)+
  xlab("cycleday from menstruation")+
  ylab("% of reported breasts tenderness")+
  scale_color_manual(values = cols$pill_trans)+
  guides(color = FALSE) 
g

ggsave(filename = paste0(IO$panels, "3B_pill_transition_increase_decrease.pdf"), plot = g, width = viz$full_width/4*3*viz$scale, height = viz$full_width/5*viz$scale)



# g = ggplot(users_subset, aes(y = dist_u_clusters,x = user_id, fill = user_cluster))+
#   geom_bar(stat = "identity", width = 0.7) + coord_flip()+
#   guides(fill = FALSE)+ xlab("")+ylab("distance")+
#   scale_y_continuous(breaks = c(0,1), minor_breaks = seq(0,1.5,by = 1/2), limits = c(0,1.2))+
#   scale_x_discrete(labels = NULL, expand = c(0,0))+
#   scale_fill_manual(values = cols$clusters_4)+
#   theme(
#     strip.background = element_blank(),
#     strip.text.y = element_blank()
#   )
# g




agg_u_wide$symptoms_change = factor(agg_u_wide$symptoms_change, levels = c("increased\nsymptoms","decreased\nsymptoms"))

g = ggplot(agg_u_wide, aes(x = symptoms_change)) + 
  geom_bar(aes(y = (..count..)/sum(..count..)), width = 0.5) + coord_flip() + 
  xlab("")+ylab("% of users")+
  scale_y_continuous(labels=percent)+
  scale_x_discrete(labels = NULL)
g

ggsave(filename = paste0(IO$panels, "3C_pill_transition_increase_decrease_percent_users.pdf"), plot = g, width = viz$full_width/7*viz$scale, height = viz$full_width/5*viz$scale)

```


```{r pill_perturbation_analysis pill transition overall trend in time increase vs decrease 2}

agg = aggregate(type ~ user_id + cycle_nb_from_pill + pill_TB_increase, days[(days$type == "tender_breasts")&!is.na(days$cycleday_m_D),], length)
colnames(agg)[colnames(agg) == "type"] = "n_tender_breasts"

ggplot(agg, aes(x = cycle_nb_from_pill,y = n_tender_breasts,  group = user_id )) + geom_line(alpha = 0.05, size = 1) + facet_grid(pill_TB_increase~.)+ xlim(c(-10,10))

ggplot(agg, aes(x = cycle_nb_from_pill,y = n_tender_breasts,  group = user_id )) + geom_line(alpha = 0.05, size = 1) + facet_grid(pill_TB_increase~.)+ xlim(c(-10,10)) + ylim(c(0,10))



ggsave(filename = paste0(IO$panels, "3C_pill_transition_increase_decrease_2.pdf"), plot = g, width = viz$full_width/2*viz$scale, height = viz$full_width/5*viz$scale)

 


```


